language: php
sudo: false

dist: trusty
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services: mysql

before_script:
  - mysql -e 'create database if not exists objectiveweb;'
  - composer install

script: vendor/bin/phpunit test/